---
- name: Clone repository
  become: true
  git:
    repo: "{{ repo_url }}"
    dest: "{{ source_dir }}/{{ repo_name }}"
    version: "{{ revision }}"
    force: true

- name: Check if package has been already installed
  changed_when: false
  failed_when: false
  shell:
    cmd: "which {{ repo_name }}"
  register: repo_path

- name: "Install {{ repo_name }}"
  become: true
  when: "repo_path.stdout == ''"
  shell: "{{ build_command }}"
