---
- name: Install official apt packages
  hosts: all
  tasks:
    - name: Install apt packages
      become: true
      apt:
        name: "{{ apt_packages }}"
        state: present

- name: Install third party apt packages
  hosts: all
  tasks:
    - name: "Install third party apt packages"
      include_role:
        name: apt_third_party
      vars:
        repo_name: "{{ item.repo_name }}"
        gpg_key_url: "{{ item.gpg_key_url }}"
        repo_url: "{{ item.repo_url }}"
        component: "{{ item.component }}"
        packages: "{{ item.packages }}"
      loop: "{{ third_party_apt_packages }}"

- name: Install git based applications
  hosts: all
  tasks:
    - name: Install git based applications
      include_role:
        name: git_package
      vars:
        repo_name: "{{ item.repo_name }}"
        repo_url: "{{ item.repo_url }}"
        build_command: "{{ item.build_command }}"
        revision: "{{ item.revision }}"
      loop: "{{ git_packages }}"

- name: Script based installation
  hosts: all
  tasks:
    - name: Install script based installation
      include_role:
        name: general_package
      vars:
        bin_name: "{{ item.bin_name }}"
        install_command: "{{ item.install_command }}"
      loop: "{{ general_packages }}"
